server:
  port: 8888
spring.cloud.config.server.git:
  uri: git@github.com:mmtondreau/spring-boot-config.git
  clone-on-start: true
  private-key: |
    -----BEGIN EC PRIVATE KEY-----
    Proc-Type: 4,ENCRYPTED
    DEK-Info: AES-128-CBC,F88DCDE18EFEA74CE9445BF42CA8B41C

    q+wgxVzyJ2VuVvUdgVbcgn0meJCbUjaG5pzrUgfe+kIomXragv1h06V/pDuSnQzO
    lFt39NywByVVnjfydA1+jAGQwqCWLtZUArlVZJ9iIr+l9Iy0K5F4ekonMKaM/SSr
    OycAH815yUq+Ou3HUkAb1HrIO8L/qWntPnHSh+D8pQE=
    -----END EC PRIVATE KEY-----
  passphrase: ${github-config-password}
  ignore-local-ssh-settings: true

