management.endpoints.web.exposure.include: info,health,refresh
management:
  endpoint:
    restart:
      enabled: true
    refresh:
      enabled: true
    health:
      show-details: always
    info:
      enabled: true
my.pingMessage: error
logging:
  level:
    root: INFO
db:
  url: jdbc:postgresql://${db.url:#{localhost:5432/tonberry}}
  username: ${db.username}
  password: ${db.password}
spring:
  datasource:
    url: jdbc:postgresql://${db.url:#{localhost:5432/tonberry}}
    username: ${db.username}
    password: ${db.password}
  r2dbc:
    username: ${db.username}
    password: ${db.password}
    url: r2dbc:postgresql://${db.url:#{localhost:5432/tonberry}}
  flyway:
    url: jdbc:postgresql://${db.url:#{localhost:5432/tonberry}}
    schemas: flyway
    user: ${db.username}
    password: ${db.password}