management.endpoints.web.exposure.include: info,health,refresh
management:
  endpoint:
    restart:
      enabled: true
    refresh:
      enabled: true
    health:
      show-details: always
    info:
      enabled: true
my.pingMessage: error
logging:
  level:
    root: INFO
db:
  url: ${db.url.jdbc:#{jdbc:postgresql://localhost:5432/tonberry}}
  username: tonberry
  password: password123
spring:
  datasource:
    url: ${db.url.jdbc:#{jdbc:postgresql://localhost:5432/tonberry}}
    username: ${db.username}
    password: ${db.password}
  r2dbc:
    username: ${db.username}
    password: ${db.password}
    url: ${db.url.r2dbc:#{r2dbc:postgresql://localhost:5432/tonberry}}
  flyway:
    url: ${db.url.jdbc:#{jdbc:postgresql://localhost:5432/tonberry}}
    schemas: flyway
    user: ${db.username}
    password: ${db.password}