spring:
  application:
    name: "ChildOne"
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
