services:
  childone:
    image: tonberry/childone:latest
    links:
      - eureka
    ports:
      - 8081:8080
      - 9991:9990
  childtwo:
    image: tonberry/childtwo:latest
    links:
      - eureka
    ports:
      - 8082:8080
      - 9992:9990
  parent:
    image: tonberry/parent:latest
    links:
      - childone
      - childtwo
      - eureka
    ports:
      - 8080:8080
      - 9990:9990
  eureka:
    image: tonberry/eurekaserver:latest
    ports:
      - 8761:8761
      - 9993:9990
