services:
  childone:
    image: tonberry/childone:latest
    environment:
      - db.password=password123
      - db.username=tonberry
      - db.url.jdbc=jdbc:postgresql://db:5432/tonberry
      - db.url.r2dbc=r2dbc:postgresql://db:5432/tonberry
    links:
      - eureka
      - config
      - db
    ports:
      - 8081:8080
      - 9991:9990
  childtwo:
    image: tonberry/childtwo:latest
    links:
      - eureka
      - config
    ports:
      - 8082:8080
      - 9992:9990
  parent:
    image: tonberry/parent:latest
    links:
      - childone
      - childtwo
      - eureka
      - config
    ports:
      - 8080:8080
      - 9990:9990
  eureka:
    image: tonberry/eurekaserver:latest
    ports:
      - 8761:8761
      - 9993:9990
    links:
      - config
  config:
    image: tonberry/config:latest
    ports:
      - 8888:8888
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=tonberry
      - POSTGRES_DB=tonberry
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
