spring:
  application:
    name: "ChildTwo"
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: ${eurekaZone:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
