spring:
  application:
    name: "Parent"
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
resilience4j:
  retry:
    instances:
      ChildOne:
        maxRetryAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.lang.Exception
