server:
  port: 8080
spring:
  application:
    name: "Parent"
  devtools.remote.secret: super$ecret
eureka:
  client:
    service-url:
      defaultZone: ${eurekaZone:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
resilience4j:
  retry:
    instances:
      ChildOne:
        maxRetryAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.lang.Exception
feign:
  circuitbreaker:
    enabled: true